# cms

production: &production
  # Ajax layout
  ajax_layout: true
  
  # Static files
  serve_static_pages: true
  serve_static_layouts: false
  
  # HTML editor (ckeditor, tinymce)
  html_editor: ckeditor

test:
  <<: *production

development:
  <<: *production
